spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://${data.url:127.0.0.1}:${data.port:3306}/app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${data.username:root}
    password: ${data.password:}
  # 验证数据库
  jpa:
    hibernate:
      ddl-auto: validate
