spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://${datasource.url:127.0.0.1}:${datasource.port:3306}/app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${datasource.username:root}
    password: ${datasource.password:root}
  # 验证数据库
  jpa:
    hibernate:
      ddl-auto: validate
  # 启用 flyway
  flyway:
    enabled: true
