mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
app:
  encrypt:
    rsa:
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzh8ZTBh8RgkQErOpbyp0
        QVry3E5bqxKmkfkQKo7MbW6gn3XliZBfl4U4SJmDSpb4wWGXLHqXQUmRME9don8r
        YIshXZ0BGJN/XFml7sxosvNLXWbwqWMXiaiqC60VSDNkGc/CO3iWWwhQz2qVTEmH
        IOF3avienssVSW2P6y0OfVSeTnmTR9ILdeDVB4nKm3HieriU+JivK4P6Yj1Dbs7t
        1NQkeoVgPYjp2UkpQhPNX2oJx9NObula18r7LVGI4rDBxv5c4q/fnU+tOGaqgKZY
        uYD6MHV5U8QPazqBju0yUj4mPFDPT1RGOk7SASlAkrrKqgU96dDq8hNIGsmbbAs2
        AQIDAQAB
        -----END PUBLIC KEY-----
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDOHxlMGHxGCRAS
        s6lvKnRBWvLcTlurEqaR+RAqjsxtbqCfdeWJkF+XhThImYNKlvjBYZcsepdBSZEw
        T12ifytgiyFdnQEYk39cWaXuzGiy80tdZvCpYxeJqKoLrRVIM2QZz8I7eJZbCFDP
        apVMSYcg4Xdq+J6eyxVJbY/rLQ59VJ5OeZNH0gt14NUHicqbceJ6uJT4mK8rg/pi
        PUNuzu3U1CR6hWA9iOnZSSlCE81fagnH005u6VrXyvstUYjisMHG/lzir9+dT604
        ZqqApli5gPowdXlTxA9rOoGO7TJSPiY8UM9PVEY6TtIBKUCSusqqBT3p0OryE0ga
        yZtsCzYBAgMBAAECggEABZ3/WH2KVXZFw9y1j1v+0xEhcTOJd/4IIA5DjIVbuNe8
        9NuHp9oRYNW2lPPqCgxXNx3rusCUgqj4lfJzwMvqaLUh8aUntH3AiMnApeNYLxhG
        Q4Ncp6EVsSCxkaPj4pXT8ogg6PH+VvjBCwYCj5OpZRH/6SBhYj5ylA+yTlxp+qxZ
        HSyijSFUYmSClq0QEJIoNXPAe+y2hys59glXf9VFB+V4rhYzMzAhHBYHmgj/KpxM
        hWfhmlXVQ4vTjvVz9GJoBMYRLDoMq/s5SZXX4rUZzYgKXSna83g2mtzQ4ZEn+CJn
        p+tgswGUmp/V5mZY3y/sBdh5j5/aOiUv0aLKvMhBCQKBgQD4UZ6jVYOJUXa8lFVk
        380eatuw3V/FOowyfqyKe1vmn6aCu+x/MQUkYpida3W+aQtPZTAf7CjkoHWh+IUU
        zNRinZpFjl5WjrevmzkTR3dd1M5tT6b//st5dbaxKT48VzUZHU7JH/tm1xGr6QAd
        gemsZ2nhkA03udmdR+22SaKjEwKBgQDUf1Pz/l0yxfhukaRhfEHAZCaTT4MY+Qes
        L+uqKYVAYBt9HRLRXpmEEjC7/YTyEIi0+xcj322roGLzUwqH46QgNf4K9dPX41Il
        oeO0YpwhN5GZCFYN7QcyCs/RxpLu6lrIjzxqwKad/yBn/uXfejL8wKwSqUHbpBlH
        OtWI4ulRGwKBgAIkCf8UfKbRafmkObw95bHOcAhtUCcOIylISEqFV7x8Qd48qoRK
        MuYmZ3Rr+b7jfvJ3R9vumEeoTntP/i24ulgDTdItsQiEAHdmGi7dXd0UOZddqW3p
        j22Do0iRt3Sjt9R4mTZIrU0sq31U6+hVN2OCHLqSGFsTohmmBhmdNua7AoGAO2nu
        e0YfoNahg6jNIUSwza4y6vVMXmsirg4oAkfhrgIxLWY3oLqmibrcTXOw/E2LK68Y
        5TrPWzFY+Ve6lgwcE7WE9mONe8tfaI4/MGxx4we6eeNOzE39uQw01x6CbrKv92u1
        JNQAwiRXVzx54WY1Y14rvnv8ogDb4IKeuctYGQkCgYBRPerN/0Am4fGoMfybTz/O
        uQjE+bhSFTu2AB7q8nVF4bPJ5FFwhvsb69JGSy4zIvp4bzkmHaGQMWJIKayr3U0F
        L/PqphRVmK2/OleIhSXz0HV9KTBu9bzQAR1428k7YH4wM/2tRP9HJWbezXo8PNlx
        4mBFCi5KrExQ02j3zYzFdw==
        -----END PRIVATE KEY-----