spring:
  profiles:
    active: github
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
---
spring:
  profiles: develop
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
---
spring:
  profiles: github
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root