mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root