SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE user (
    id INTEGER(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
