flyway:
  auth:
    url: jdbc:mysql://127.0.0.1:3306/auth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    location: db/migration/auth