name: Java CI Workflow

on: pull_request

jobs:
  build:
    name: Project Test And Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Shutdown default mysql
        run: sudo service mysql stop
