name: Java CI Workflow

on: pull_request

jobs:
  build:
    name: Project Test And Build
    runs-on: ubuntu-latest
    services:
      mysql:
        name: mysql
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3309:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: View docker images
        run: docker ps
