name: Java CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Project Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Shutdown Default MySQL
        run: sudo service mysql stop
      - name: Create MySQL Database Auth
        uses: icomponent/mysql-action@master
        with:
          VERSION: 5.7
          CONTAINER_NAME: mysql
          PORT_MAPPING: 3307:3306
          ROOT_PASSWORD: root
          DATABASE: auth
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Migrate Module
        run: gradle migrate:bootRun
      - name: Core Module
        run: gradle core:test
      - name: Common Module
        run: gradle common:test
      - name: Auth Module
        run: gradle auth:test